import type { Team, Application, Deadline, User } from "./types"

export const currentUser: User = {
  id: "1",
  name: "Sarah Chen",
  email: "sc2345@cornell.edu",
  role: "student",
  avatar: "/placeholder.svg?height=40&width=40",
  major: "Computer Science",
  year: "Sophomore",
}

export const teams: Team[] = [
  {
    id: "1",
    name: "Cornell Rocketry",
    description: "Design, build, and launch high-powered rockets",
    category: "Aerospace",
    subteams: ["Software", "Avionics", "Propulsion", "Structures", "Recovery"],
    tags: ["Software", "Avionics", "Propulsion"],
    hoursPerWeek: "10-15 hrs/week",
    memberCount: 45,
    dueDate: "Feb 15, 2024",
    imageColor: "bg-emerald-500",
    icon: "rocket",
  },
  {
    id: "2",
    name: "CUAir",
    description: "Autonomous aerial vehicle systems",
    category: "Flight",
    subteams: ["Computer Vision", "Controls", "Mechanical", "Ground Station"],
    tags: ["Computer Vision", "Controls", "Mechanical"],
    hoursPerWeek: "12-18 hrs/week",
    memberCount: 60,
    dueDate: "Feb 15, 2024",
    imageColor: "bg-rose-400",
    icon: "plane",
  },
  {
    id: "3",
    name: "Cornell Baja",
    description: "Off-road racing vehicle design",
    category: "Racing",
    subteams: ["Suspension", "Powertrain", "Frame", "Ergonomics"],
    tags: ["Suspension", "Powertrain", "Frame"],
    hoursPerWeek: "15-20 hrs/week",
    memberCount: 35,
    dueDate: "Feb 15, 2024",
    imageColor: "bg-teal-500",
    icon: "car",
  },
  {
    id: "4",
    name: "Cornell AppDev",
    description: "Mobile and web app development",
    category: "Software",
    subteams: ["iOS", "Backend", "Design", "Android"],
    tags: ["iOS", "Backend", "Design"],
    hoursPerWeek: "8-12 hrs/week",
    memberCount: 50,
    dueDate: "Feb 15, 2024",
    imageColor: "bg-pink-500",
    icon: "code",
  },
  {
    id: "5",
    name: "Health Tech Initiative",
    description: "Medical device innovation",
    category: "Biomedical Engineering",
    subteams: ["Biomedical", "Electronics", "Software", "Regulatory"],
    tags: ["Biomedical", "Electronics", "Software"],
    hoursPerWeek: "8-12 hrs/week",
    memberCount: 30,
    dueDate: "Feb 15, 2024",
    imageColor: "bg-cyan-500",
    icon: "heart",
  },
  {
    id: "6",
    name: "Solar Car Team",
    description: "Solar-powered vehicle engineering",
    category: "Environmental",
    subteams: ["Electrical", "Mechanical", "Business", "Strategy"],
    tags: ["Electrical", "Mechanical", "Business"],
    hoursPerWeek: "12-15 hrs/week",
    memberCount: 40,
    dueDate: "Feb 15, 2024",
    imageColor: "bg-lime-500",
    icon: "sun",
  },
]

export const applications: Application[] = [
  {
    id: "1",
    teamId: "1",
    teamName: "Cornell Rocketry",
    subteam: "Software Subteam",
    status: "in-progress",
    progress: 60,
    dueDate: "Feb 15",
  },
  {
    id: "2",
    teamId: "2",
    teamName: "CUAir",
    subteam: "Avionics Team",
    status: "submitted",
    progress: 100,
    dueDate: "Feb 15",
    submittedDate: "Jan 28",
  },
  {
    id: "3",
    teamId: "3",
    teamName: "Cornell Baja",
    subteam: "Suspension Team",
    status: "draft",
    progress: 20,
    dueDate: "Feb 15",
  },
]

export const deadlines: Deadline[] = [
  {
    id: "1",
    teamName: "Cornell Rocketry",
    type: "application",
    date: "15 FEB",
    time: "11:59 PM",
  },
  {
    id: "2",
    teamName: "Cornell Baja",
    type: "application",
    date: "15 FEB",
    time: "11:59 PM",
  },
  {
    id: "3",
    teamName: "CUAir",
    type: "interview",
    date: "20 FEB",
    time: "3:00 PM",
  },
]

export const categories = [
  "All Categories",
  "Car",
  "XR",
  "Biomedical Engineering",
  "Structural Engineering",
  "Flight",
  "Boat",
  "Environmental",
  "Software",
  "Drone and Bot",
  "Autonomous Water",
  "Racing",
  "Aerospace",
  "Transportation",
]

export const timeCommitments = [
  "All Time Commitments",
  "< 8 hrs/week",
  "8-12 hrs/week",
  "12-18 hrs/week",
  "> 18 hrs/week",
]

export const recruitingStats = {
  activeTeams: 18,
  applicationsStarted: 3,
  submitted: 1,
  interviewsScheduled: 2,
  daysRemaining: 3,
  deadline: "February 15, 2024 at 11:59 PM",
}
